import type { Metadata } from "next";
import { FileText } from "lucide-react";
import { getAdminReports } from "@/server/admin-queries";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { StatusBadge } from "@/components/ui/status-badge";
import { EmptyState } from "@/components/ui/empty-state";
import { formatDate } from "@/lib/utils";

export const metadata: Metadata = { title: "Reports" };

export default async function AdminReportsPage() {
  const reports = await getAdminReports();
  return (
    <>
      <PageHeader eyebrow="Internal" title="Reports" description="Reports generated by customers. Each is a frozen snapshot of their metrics at generation time." />
      {reports.length === 0 ? (
        <EmptyState icon={FileText} title="No reports generated yet" />
      ) : (
        <div className="overflow-hidden rounded-xl border border-line bg-white shadow-card">
          <Table>
            <TableHeader>
              <TableRow className="hover:bg-transparent">
                <TableHead>Report</TableHead>
                <TableHead>Customer</TableHead>
                <TableHead>Period</TableHead>
                <TableHead>Visibility</TableHead>
                <TableHead>AEO</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Generated</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((r) => {
                const d = JSON.parse(r.dataJson) as { visibility?: { score?: number }; visibilityScore?: number; audit?: { overallScore?: number }; aeoScore?: number };
                return (
                  <TableRow key={r.id}>
                    <TableCell className="font-medium text-ink">{r.title}</TableCell>
                    <TableCell className="whitespace-nowrap">
                      {r.organization.name} <span className="text-ink-faint">· {r.website.domain}</span>
                    </TableCell>
                    <TableCell className="whitespace-nowrap text-ink-muted">
                      {formatDate(r.periodStart)} – {formatDate(r.periodEnd)}
                    </TableCell>
                    <TableCell className="font-semibold tabular-nums">{d.visibility?.score ?? d.visibilityScore ?? "—"}</TableCell>
                    <TableCell className="font-semibold tabular-nums">{d.audit?.overallScore ?? d.aeoScore ?? "—"}</TableCell>
                    <TableCell>
                      <StatusBadge status={r.status} />
                    </TableCell>
                    <TableCell className="whitespace-nowrap text-ink-muted">{formatDate(r.createdAt)}</TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </div>
      )}
    </>
  );
}
